name = "ModelObjectTools"
uuid = "7833e302-2a28-4046-a4d6-a6c700649641"
authors = ["Daniel Haanwinckel <junqueira.d@gmail.com> and contributors"]
version = "1.0.0"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
